package it.polimi.ingsw.controller;

import it.polimi.ingsw.ServerApp;
import it.polimi.ingsw.exception.*;
import it.polimi.ingsw.model.*;
import it.polimi.ingsw.model.commonGoalCard.*;
import it.polimi.ingsw.network.message.MoveRequestMessage;
import it.polimi.ingsw.network.message.ResponseMessage;
import it.polimi.ingsw.view.VirtualView;

import java.io.*;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.TimeoutException;
import java.util.logging.Logger;

/** Controller of the implemented MVC pattern.<br/>
 *  Its task is to interface View and Model.<br/>
 *  Through the View (VirtualView class), this class communicates with a specific user, receiving input,
 *  communicating results and updates to the Model in a completely transparent manner. <br/>
 *  Thanks to the VirtualView, in fact, there is a clear separation between the management of the game and the
 *  management of communication with the user, through which it is also possible to initialise a game locally
 *  (where all the player can play through CLI in the server, especially useful in debug phases).<br/>
 *  In the context of the game, this class takes care of the management of the turn and consequently performs checks
 *  to manage every event connected with the user, Such as disconnections, and choosing to pass the turn.<br/>
 *  Each instance of this class identifies a specific MyShelfie match.<br/>
 *  It is created by ServerApp, which starts the game as soon as a waiting room is complete.<br/>
 *  In order to implement the possibility of managing several matches simultaneously, each instance of this class
 *  is managed in a separate Thread.<br/>
 *  Considering that ServerApp, for simplicity and clarity of implementation, does not maintain a status of the
 *  launched Threads, as the last action of the run() method, this class takes care of deleting players from
 *  the Map of Players in the ServerApp.<br/>
 *  <br/>
 *  The Controller implements a Persistence functionality. The controller use as save-point a unique filename
 *  generated by ServerApp. At the end of each turn (excluding the last for usability issues), in a point where
 *  we have a consistent state, it serializes and saves the state of Game obj in the file indicated by the filename.
 *  The restoration of a savepoint do not affect the flow of the controller, thanks to the run() structure.
 *  Ensuring a 1-to-1 relationship between files and matches we can avoid synchronization issues.
 *  Also, using different files, increase usability of the server, giving an operator the possibility to manually
 *  change them.
 *  <br/>
 *  We can briefly schematise the match-making flow in this way: ServerApp --> Patrick --> Game --> All the rest of the model
 *
 * @see ServerApp
 * @see Game
 * @see VirtualView
 * @since 1.0
 * @version 1.0
 * */
public class Patrick extends Thread{

    public Game game;
    private String name;
    public VirtualView virtualView;
    public GameView gameView;
    private final Logger logger = Logger.getLogger("Logger");
    private boolean isOffline;

    /**General Constructor for new Local and Remote matches.
     * @param players List of players in the match.
     * @param name Name of the match. If it is OfflineGame, we start a LocalMatch on server.
     *             Otherwise, is considered as an absolute path to save progresses into.*/
    public Patrick(List<Player> players, String name){

        this.name = name;
        this.virtualView = name.equals("OfflineGame") ? new VirtualView() : new VirtualView(players) ;
        this.isOffline = name.equals("OfflineGame");
        //We initialise the class with all the components we need

        List<CommonGoalCard> deckCommonCard = createDeckCommonCard();         //Creating commonGoalCards

        List<PersonalGoalCard> deckPersonalCard = createDeckPersonalCard();   //Creating personalGoalCards

        List<Tile> tiles = createArrayTile();                                 //Creating the tiles

        EndGameToken endGameToken = new EndGameToken();                       //Creating the endgameToken

        List<CommonGoalCard> deckCommonGoalCardInGame = drawCommonGoalCard(deckCommonCard, players.size());

        List<PersonalGoalCard> deckPersonalGoalCardInGame = drawPersonalGoalCard(deckPersonalCard, players.size());

        List<PlayerInGame> playersInGame = createPlayers(players);


        //Players are passed from the server to Patrick who passes them on to the game that is generated in the
        //form of PlayerInGame

        //Creating game, game view and establishing Observer/Observable relationship
        game = new Game(name, playersInGame, deckPersonalGoalCardInGame, endGameToken, tiles, deckCommonGoalCardInGame);
        gameView = new GameView(game);
        game.addObserver(gameView);
        gameView.addObserver(virtualView);

    }

    /**Constructor specific for restoring saved matches.
     * @param players List of players in the match.
     * @param filepath Absolute file path from which we restored the state and progresses.
     * @param game Restored state of the match.*/
    public Patrick(List <Player> players, String filepath, Game game){

        this.isOffline = false;
        this.name = filepath;
        this.virtualView = new VirtualView(players) ;
        //We initialise the class with all the components we need

        this.game = game;
        gameView = new GameView(game);
        game.addObserver(gameView);
        gameView.addObserver(virtualView);

        game.nextTurn();

    }

    public void run() {


        do {

            if(!isOffline){
                anticipatedEndgame(120);}

            boolean undoAction;
            boolean passAction = false;

            String turnPlayerName = game.getTurnPlayerName();
            logger.info("Propagating STARTTURN event.");
            game.setChangedAndNotifyObservers(Game.Event.STARTTURN);
            logger.info("Turn of "+turnPlayerName);

            do {

                List<Position> posix;
                List<Tile> tiles = new ArrayList<>(3);
                List<Tile> sortedTiles;


                //starting the pick request
                try {
                    logger.info("Sending pick move notification to "+turnPlayerName);
                    virtualView.moveNotification(turnPlayerName, MoveRequestMessage.Choice.PICKING);

                } catch (IOException e) {
                    passAction = true;
                    logger.warning("Caught IOException on pick notification to "+turnPlayerName+". Passing turn");
                }

                boolean repeat = true;
                while (repeat && !passAction) {
                    try {

                        logger.info("Waiting for PickMoveMessage");
                        posix = virtualView.pickTilesMove(turnPlayerName, 180);
                        logger.info("Chosen posix:"+posix);
                        logger.info("Pickable Tiles:"+game.getBoard().combinationOfTakeableTilesForTurnPlayer(game.getTurnPlayerBookshelf()));
                        tiles = game.pickTileFromBoard(posix);
                        logger.info("Chosen tiles:"+tiles);

                        try {
                            virtualView.responseNotification(turnPlayerName, ResponseMessage.ResponseType.PICKCONFIRMATION);
                        } catch (IOException ex) {
                            passAction = true;
                            logger.warning("IOException on "+turnPlayerName+" on confirmation for Picking Move");
                        }

                        repeat = false;
                    } catch (NonPickableTilesException e) {
                        try {
                            virtualView.responseNotification(turnPlayerName, ResponseMessage.ResponseType.NONPICKABLETILES);
                        } catch (IOException ex) {
                            passAction = true;
                            logger.warning(turnPlayerName+" has passed after NonPickableTilesException due to IOException.");
                        }
                        logger.info("In-game error for Pick for "+turnPlayerName);
                    } catch (StreamCorruptedException exc){

                        logger.warning("Caught StreamCorruptedException on PPicking move. Passing the turn.\n ");
                        exc.printStackTrace(System.out);

                        passAction = true;
                    } catch (IOException | PassedMoveException | TimeoutException exc ) {
                        logger.warning("Caught "+ exc.getClass()+" on Picking move. Passing the turn.");
                        //TODO DA verificare
                        try {
                            virtualView.responseNotification(turnPlayerName, ResponseMessage.ResponseType.NONPICKABLETILES);
                        } catch (IOException e) {
                            throw new RuntimeException(e);
                        }

                        passAction = true;
                    }
                }

                try {
                    virtualView.moveNotification(turnPlayerName, MoveRequestMessage.Choice.SORTING);
                } catch (IOException e) {
                    passAction = true;
                    logger.warning("Caught IOException on sort notification to "+turnPlayerName+". Passing turn");

                }

                //starting the sort move
                repeat=true;
                while (repeat && tiles.size() >=  1 && !passAction) {
                    try {
                        sortedTiles = virtualView.sortTilesMove(turnPlayerName, tiles,180);
                        logger.info("Chosen sorted:"+sortedTiles);
                        game.sortTileToInsert(sortedTiles);

                        try {
                            virtualView.responseNotification(turnPlayerName, ResponseMessage.ResponseType.SORTCONFIRMATION);
                        } catch (IOException ex) {
                            passAction = true;
                            logger.warning("IOException on "+turnPlayerName+" on confirmation for Sorting Move");
                        }

                        repeat = false;
                    } catch (BadSortedTilesListException e) {
                        try {
                            virtualView.responseNotification(turnPlayerName, ResponseMessage.ResponseType.BADSORTEDTILESLIST);
                        } catch (IOException ex) {
                            passAction = true;
                            logger.info("In-game error for Sort for "+turnPlayerName);

                        }
                        logger.warning("There is an error in the sorting. Retry.");
                    } catch (IOException | PassedMoveException | TimeoutException exc) {
                        logger.warning("Caught "+ exc.getClass()+" on Sorting move. Passing the turn.");
                        try {
                            virtualView.responseNotification(turnPlayerName, ResponseMessage.ResponseType.BADSORTEDTILESLIST);
                        } catch (IOException e) {
                            throw new RuntimeException(e);
                        }
                        passAction = true;
                    }
                }

                try {
                    virtualView.moveNotification(turnPlayerName, MoveRequestMessage.Choice.COLUMNCHOICE);
                } catch (IOException e) {
                    passAction = true;
                    logger.warning("Caught IOException on column choice notification to "+turnPlayerName+". Passing turn");
                }

                //starting the choose move
                repeat=true;
                while (repeat && !passAction) {
                    try {
                        game.chooseColumn(virtualView.chooseColumnMove(turnPlayerName,180));

                        try {
                            virtualView.responseNotification(turnPlayerName, ResponseMessage.ResponseType.COLCONFIRMATION);
                        } catch (IOException ex) {
                            passAction = true;
                            logger.warning("IOException on "+turnPlayerName+" on confirmation for Choosing-column Move");
                        }

                        repeat = false;
                    } catch (NotEnoughFreeBoxesInColumnException e) {
                        try {
                            virtualView.responseNotification(turnPlayerName, ResponseMessage.ResponseType.NOTENOUGHFREEBOXESINCOLUMN);
                        } catch (IOException ex) {
                            passAction = true;
                            logger.warning(turnPlayerName+" has passed after NotEnoughFreeBoxesInColumnException due to IOException.");

                        }
                        logger.info("In-game error for Column choice for "+turnPlayerName);
                    } catch (IOException | PassedMoveException | TimeoutException exc) {
                        logger.warning("Caught "+ exc.getClass()+" on Column choosing move. Passing the turn.");
                        try {
                            virtualView.responseNotification(turnPlayerName, ResponseMessage.ResponseType.NOTENOUGHFREEBOXESINCOLUMN);
                        } catch (IOException e) {
                            throw new RuntimeException(e);
                        }
                        passAction = true;
                    }
                }



                if (passAction) {
                    //if the turn is passed no confirmation is asked
                    undoAction = false;
                }else{

                    try {
                        virtualView.moveNotification(turnPlayerName, MoveRequestMessage.Choice.CONFIRMATION);
                        undoAction = !(virtualView.turnConfirmation(turnPlayerName, 180));
                        if (undoAction) {
                            game.removeTilesChosenByTurnPlayerInBookshelf();
                        }

                    } catch (IOException | TimeoutException exc) {
                        logger.warning("Caught "+ exc.getClass()+" on confirmation notification to "+turnPlayerName+". Considering the turn valid.");
                        undoAction = false;
                    }
                }


            } while (undoAction);

            if (!passAction) {
                logger.warning("Finalizing the turn.");
                game.removeTilesChosenAndRefillBoard();
                logger.warning("Changes applied to board.");
                game.checkCommonGoalCard();
                logger.warning("Common Goal card Goals checked for "+turnPlayerName);
                game.checkEndgame();
                logger.warning("Endgame triggers checked for "+turnPlayerName+" bookshelf");

                if (!game.isLastTurn()) {
                    persistence();
                    logger.warning("Saving match state in filesystem");
                }



            }



        } while(game.nextTurn());
        game.endGame();

        logger.info("Propagating ENDGAME event.");
        game.setChangedAndNotifyObservers(Game.Event.ENDGAME);

        cleanup();

    }


    /**
     * It creates the complete deck, one of each type, of all twelve commonGoalCards through all its respective subclasses.
     *
     * @return a list of twelve commonGoalCards.
     */
    private static List<CommonGoalCard> createDeckCommonCard() {

        List<CommonGoalCard> deckCommonCard = new ArrayList<>(12);

        deckCommonCard.add(new C1());
        deckCommonCard.add(new C2());
        deckCommonCard.add(new C3());
        deckCommonCard.add(new C4());
        deckCommonCard.add(new C5());
        deckCommonCard.add(new C6());
        deckCommonCard.add(new C7());
        deckCommonCard.add(new C8());
        deckCommonCard.add(new C9());
        deckCommonCard.add(new C10());
        deckCommonCard.add(new C11());
        deckCommonCard.add(new C12());

        return deckCommonCard;
    }

    /**
     * It creates the complete deck of all 12 personalGoalCards using 12 different arrays. Each of the 12 arrays initialises
     * a different personalGoalCard via an array of positions.
     * The bookshelf constructor uses the positions according to the following scheme:
     *         posix[0] greenTile row                posix[1] greenTile column
     *         posix[2] whiteTile row                posix[3] whiteTile column
     *         posix[4] yellowTile row               posix[5] yellowTile column
     *         posix[6] BlueTile row                 posix[7] blueTile column
     *         posix[8] LightBlueTile row            posix[9] lightBlueTile column
     *         posix[10] PinkTile row                posix[11] pinkTile column
     *
     * @return a list of twelve personalGoalCards.
     */
    private static List<PersonalGoalCard> createDeckPersonalCard() {

        int[] posix1 = {1, 4, 2, 3, 3, 1, 0, 2, 5, 2, 0, 0};
        int[] posix2 = {2, 0, 3, 4, 2, 2, 5, 4, 4, 3, 1, 1};
        int[] posix3 = {3, 1, 5, 0, 1, 3, 1, 0, 3, 4, 2, 2};
        int[] posix4 = {4, 2, 4, 1, 0, 4, 2, 2, 0, 2, 3, 3};
        int[] posix5 = {5, 3, 3, 2, 5, 0, 3, 1, 1, 1, 4, 4};
        int[] posix6 = {0, 4, 2, 3, 4, 1, 4, 3, 0, 2, 5, 0};
        int[] posix7 = {0, 0, 5, 2, 4, 4, 1, 3, 3, 0, 2, 1};
        int[] posix8 = {1, 1, 4, 3, 5, 3, 0, 4, 2, 2, 3, 0};
        int[] posix9 = {2, 2, 3, 4, 0, 2, 5, 0, 4, 1, 4, 4};
        int[] posix10 = {3, 3, 2, 0, 1, 1, 4, 1, 0, 4, 5, 3};
        int[] posix11 = {4, 4, 1, 1, 2, 0, 3, 2, 5, 3, 0, 2};
        int[] posix12 = {5, 0, 0, 2, 4, 4, 2, 2, 3, 3, 1, 1};


        List<PersonalGoalCard> deckPersonalCard = new ArrayList<>(12);

        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix1),"/Graphics/personal_goal_cards/Personal_Goals.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix2),"/Graphics/personal_goal_cards/Personal_Goals2.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix3),"/Graphics/personal_goal_cards/Personal_Goals3.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix4),"/Graphics/personal_goal_cards/Personal_Goals4.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix5),"/Graphics/personal_goal_cards/Personal_Goals5.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix6),"/Graphics/personal_goal_cards/Personal_Goals6.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix7),"/Graphics/personal_goal_cards/Personal_Goals7.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix8),"/Graphics/personal_goal_cards/Personal_Goals8.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix9),"/Graphics/personal_goal_cards/Personal_Goals9.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix10),"/Graphics/personal_goal_cards/Personal_Goals10.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix11),"/Graphics/personal_goal_cards/Personal_Goals11.png"));
        deckPersonalCard.add(new PersonalGoalCard(new Bookshelf(posix12),"/Graphics/personal_goal_cards/Personal_Goals12.png"));

        return deckPersonalCard;
    }

    /**
     * It creates, sorted randomly, a list of all 132 tiles, (22 for each of the 6 types), in the game.
     *
     * @return a list of 132 tiles (22 for each of the 6 types).
     */
    private static List<Tile> createArrayTile() {

        //We initialise one for each of the six types

        Tile greenTile = new Tile(Color.Green, Figure.Cats);
        Tile whiteTile = new Tile(Color.White, Figure.Books);
        Tile yellowTile = new Tile(Color.Yellow, Figure.Games);
        Tile blueTile = new Tile(Color.Blue, Figure.Frames);
        Tile lightBlueTile = new Tile(Color.LightBlue, Figure.Trophies);
        Tile pinkTile = new Tile(Color.Pink, Figure.Plants);

        List<Tile> tiles = new ArrayList<>(132);

        List<Tile> typeTiles = new ArrayList<>(6);

        typeTiles.add(greenTile);
        typeTiles.add(whiteTile);
        typeTiles.add(yellowTile);
        typeTiles.add(blueTile);
        typeTiles.add(lightBlueTile);
        typeTiles.add(pinkTile);

        for (Tile typeTile : typeTiles) {

            for (int i = 0; i < 22; i++) {
                tiles.add(typeTile);
            }

        }

        Collections.shuffle(tiles);

        return tiles;

    }

    /**
     * It creates a list of PlayerInGame by their respective names. Player is the representation of the client that has
     * connected, while PlayerInGame is the Player in the particular instance of the game.
     *
     * @param players list of clients that has connected to the game.
     * @return a list of PlayerInGame that represents players in the particular instance of the game.
     */
    private static List<PlayerInGame> createPlayers(List<Player> players) {

        List<PlayerInGame> playersInGame = new ArrayList<>(4);

        for (Player x : players) {
            playersInGame.add(new PlayerInGame(x.getName()));
        }

        return playersInGame;
    }

    /**
     * It draws as many personalGoalCards as there are players (maximum 4), and places them in a list.
     *
     * @param deckPersonalCard  a list of all twelve personalGoalCards
     * @param numPlayers number of players that has connected to the game.
     * @return a list of as many personalGoalCards as there are players (maximum 4).
     */
    private static List<PersonalGoalCard> drawPersonalGoalCard(List<PersonalGoalCard> deckPersonalCard, int numPlayers) {

        List<PersonalGoalCard> deckPersonalGoalCardInGame = new ArrayList<>(4);

        Collections.shuffle(deckPersonalCard);

        for (int i = 0; i < numPlayers; i++) {
            deckPersonalGoalCardInGame.add(i, deckPersonalCard.get(i));
        }

        return deckPersonalGoalCardInGame;
    }

    /**
     * It draws two commonGoalCards from the deck of all twelve commonGoalCards. Depending on the number of players, it also
     * initialises the arrayList of tokens and its values.
     *
     * @param deckCommonCard a list of all twelve commonGoalCards.
     * @param numPlayers number of players that has connected to the game.
     * @return a list of commonGoalCards that have as many tokens in their arrayList as there are connected players.
     */
    private static List<CommonGoalCard> drawCommonGoalCard(List<CommonGoalCard> deckCommonCard, int numPlayers) {

        List<CommonGoalCard> deckCommonGoalCardInGame = new ArrayList<>(2);

        Collections.shuffle(deckCommonCard);

        if (numPlayers == 2) {

            List<List<CommonToken>> commonTokenslist = new ArrayList<>();

            commonTokenslist.add(new ArrayList<>());

            commonTokenslist.get(0).add(new CommonToken(8));
            commonTokenslist.get(0).add(new CommonToken(4));

            commonTokenslist.add(new ArrayList<>());

            commonTokenslist.get(1).add(new CommonToken(8));
            commonTokenslist.get(1).add(new CommonToken(4));


            for (int i = 0; i < 2; i++) {

                deckCommonCard.get(i).setCommonTokens(commonTokenslist.get(i));

                deckCommonGoalCardInGame.add(i, deckCommonCard.get(i));

            }
        }
        if (numPlayers == 3) {

            List<List<CommonToken>> commonTokenslist = new ArrayList<>();

            commonTokenslist.add(new ArrayList<>());

            commonTokenslist.get(0).add(new CommonToken(8));
            commonTokenslist.get(0).add(new CommonToken(6));
            commonTokenslist.get(0).add(new CommonToken(4));

            commonTokenslist.add(new ArrayList<>());

            commonTokenslist.get(1).add(new CommonToken(8));
            commonTokenslist.get(1).add(new CommonToken(6));
            commonTokenslist.get(1).add(new CommonToken(4));


            for (int i = 0; i < 2; i++) {

                deckCommonCard.get(i).setCommonTokens(commonTokenslist.get(i));

                deckCommonGoalCardInGame.add(i, deckCommonCard.get(i));

            }
        }
        if (numPlayers == 4) {

            List<List<CommonToken>> commonTokenslist = new ArrayList<>();

            commonTokenslist.add(new ArrayList<>());

            commonTokenslist.get(0).add(new CommonToken(8));
            commonTokenslist.get(0).add(new CommonToken(6));
            commonTokenslist.get(0).add(new CommonToken(4));
            commonTokenslist.get(0).add(new CommonToken(2));

            commonTokenslist.add(new ArrayList<>());

            commonTokenslist.get(1).add(new CommonToken(8));
            commonTokenslist.get(1).add(new CommonToken(6));
            commonTokenslist.get(1).add(new CommonToken(4));
            commonTokenslist.get(1).add(new CommonToken(2));


            for (int i = 0; i < 2; i++) {

                deckCommonCard.get(i).setCommonTokens(commonTokenslist.get(i));

                deckCommonGoalCardInGame.add(i, deckCommonCard.get(i));

            }
        }


        return deckCommonGoalCardInGame;


    }

    /** Persistence Implementation.
     * The method has to save the serialized state of the match in a specific directory of the filesystem.
     * The filename must be unique - using datetime and thread id.
     * */
    private void persistence(){

        String filename = this.name;
        logger.info("Saving the state of the match in "+filename);
        ObjectOutputStream objectOutputStream = null;
        FileOutputStream fileOutputStream;
        try{
            fileOutputStream = new FileOutputStream(filename, false);
            objectOutputStream = new ObjectOutputStream(fileOutputStream);
            objectOutputStream.writeObject(this.game);
            logger.info(filename+" successfully overwritten.");
        } catch (IOException e) {
            logger.info("IOException on "+filename+" overwriting.");
            e.printStackTrace();
        } finally{
            try {
                assert objectOutputStream != null;

                  if (objectOutputStream != null){
                      objectOutputStream.close();
                  }


            }
            catch (IOException e) {logger.info("IOException on "+filename+" stream closing.");}
        }
    }


    /** Gracefully clean the resources on endgame.
     * 1. Remove files used for persistence.
     * 2. Remove players from PlayerInGame map in ServerApp
     * 3. Close the thread.*/
    private synchronized void cleanup(){
        logger.info("Cleaning up: STARTING.");
        File file = new File(name);
        if (file.delete()) {
            logger.info(name + " file deleted.");
        } else {
            logger.info("Cannot delete " + name+".");
        }

        logger.info("Removing players from shared PlayersInGame Map.");
        ServerApp.removePlayersFromPlayersInGameMap(game.getPlayersNames());
        logger.info("Cleaning up: DONE.");
    }

    /** Check if the there are players connected. Close the game if it is not the case.
     * Declare Winner if there is only a player left.
     * @param timeout Time in seconds to wait before declaring the anticipated endgame.
     * */
    private void anticipatedEndgame(int timeout){
        List<String> players = this.virtualView.checkConnection(this.game.getPlayersNames(), timeout);
        if(players == null){
            logger.info("No players left in the game. Closing.");
            this.cleanup();
            this.interrupt();
        }else if (players.size() == 1){
            logger.info("There is only a player left in the game. Declare Victory and Close.");
            try {virtualView.sendMessageForAnticipatedEndgame(players.get(0));} catch (IOException e) {/*NOTHING TO DO HERE*/}
            this.cleanup();
            this.interrupt();
        }
    }

}
